name: Auto update rule
on:
  workflow_dispatch:
  
  schedule:
    - cron:  '* 0/6 * * *' 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Run start-ci.sh
      run: |
        /bin/bash ./scripts/start-ci.sh
        
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *
        git commit -m "update : $(TZ=UTC-8 date "+%Y-%m-%d %H:%M:%S")"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PERSON_TOKEN }}
        branch: 'master'
