name: Auto update rule
on:
  workflow_dispatch:
  schedule:
    - cron:  '25 0/3 * * *' 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run start-ci.sh
      run: |
        /bin/bash ./scripts/start-ci.sh
        
    - name: Push artifacts to release branch
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        git fetch
        git checkout release
        
        git checkout --orphan release-orphan
        git rm -rf .

        git add ad.yaml
        git add ad-easylist.txt
        git add ad-smartdns.conf
        git add ad.conf
        git add ad.list
        git stash clear
        
        git commit -m "update : $(TZ=UTC-8 date "+%Y-%m-%d %H:%M:%S")"
        git branch -D release
        git branch -m release

    - name: GitHub Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PERSON_TOKEN }}
        branch: 'release'
        
    - name: Delete workflow
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 1
        keep_minimum_runs: 3
