name: Auto update rule
on:
  schedule:
    - cron: "0 0/6 * * *"
        workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@main
    - name: Run start-ci.sh
      run: |
        /bin/bash ./scripts/start-ci.sh
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *
        git commit -m "Auto update." -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PERSON_TOKEN }}
        branch: 'master'
